connections: # 要自动化部署的连接
    - ssh.web-01

remote_folder: "/home/guyi/corodemo" # 远端的部署文件夹

frontend: # 前端部署配置
    pre_action: # 部署前置命令
        - "pwd"
    post_action: # 部署后置命令
        - "pwd"

backend: #后端部署配置
    goos: linux # 部署目标操作系统
    goarch: amd64 # 部署目标cpu架构
    pre_action: # 布置前置命令
        - "rm /home/guyi/coredemo/gocore"
    post_action: # 部署后置命令
        - "chmod 777 /home/guyi/coredemo/gocore"
        - "/home/guyi/coredemo/gocore app restart"
