mysql:
  hostname: 127.0.0.1
  usename: root
  password: env(DB_PASSWORD)
  timeout: 1
  readtime: 2.3

default:
  driver: mysql
  hostname: localhost
  database: gocore
  username: root
  password: 12345678
  charaset: utf8mb4
  collation: utf8mb4_unicode_ci